### ISSUE TITLE
Apply column rules to index columns

### ISSUE THREAD

**Issue by jaidevd** [jaidevd/pysemantic#63]
Loading breaks if there exist column rules for a column that is supposed to be an index_col, as follows:

``` yaml
iris:
  index_col: Species
  column_rules:
    Species:
      regex: [a-z]|[A-Z]+
```
