### ISSUE TITLE
Don't complain about irrelevant schema

### ISSUE THREAD

**Issue by jaidevd** [jaidevd/pysemantic#91]
The current implementation is designed to raise exceptions when parsing the schema if it is malformed in any way. Eg:

``` yaml
foo:
  path: /foo/bar # this path exists

baz:
  path: /bar/baz # this path doesn't
```

 This should raise exceptions only when the the dataset `baz` is being loaded.
